// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"athena/src/database"
	"athena/src/services/blockchain"
	"athena/src/services/blockchain/controller"
	blockchain2 "athena/src/services/wallet-address"
	controller2 "athena/src/services/wallet-address/controller"
)

// Injectors from wire.go:

func GetContainer() *Container {
	databaseDatabase := database.GetInstance()
	blockchainRepository := blockchain.ProvideBlockchainRepository(databaseDatabase)
	blockchainService := blockchain.ProvideBlockchainService(blockchainRepository)
	blockchainController := blockchain.ProvideBlockchainController(blockchainService)
	walletAddressRepository := blockchain2.ProvideWalletAddressRepository(databaseDatabase)
	walletAddressService := blockchain2.ProvideWalletAddressService(walletAddressRepository)
	walletAddressController := blockchain2.ProvideWalletAddressController(walletAddressService)
	container := &Container{
		BlockchainController:    blockchainController,
		WalletAddressController: walletAddressController,
	}
	return container
}

// wire.go:

type Container struct {
	BlockchainController    *controller.BlockchainController
	WalletAddressController *controller2.WalletAddressController
}
