// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"athena/src/database"
	"athena/src/services/blockchain"
	"athena/src/services/blockchain/controller"
)

// Injectors from wire.go:

func GetContainer() *Container {
	databaseDatabase := database.GetInstance()
	blockchainRepository := blockchain.ProvideBlockchainRepository(databaseDatabase)
	blockchainService := blockchain.ProvideBlockchainService(blockchainRepository)
	blockchainController := blockchain.ProvideBlockchainController(blockchainService)
	container := &Container{
		BlockchainController: blockchainController,
	}
	return container
}

// wire.go:

type Container struct {
	BlockchainController *controller.BlockchainController
}
