// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"athena/src/api/http/controllers"
	"athena/src/database"
)

// Injectors from wire.go:

func GetContainer() *Container {
	databaseDatabase := database.GetInstance()
	blockchainRepository := ProvideBlockchainRepository(databaseDatabase)
	blockchainService := ProvideBlockchainService(blockchainRepository)
	blockchainController := ProvideBlockchainController(blockchainService)
	walletAddressRepository := ProvideWalletAddressRepository(databaseDatabase)
	blockchainExplorerRepository := ProvideBlockchainExplorerRepository(databaseDatabase)
	blockchainExplorerService := ProvideBlockchainExplorerService(blockchainExplorerRepository, blockchainService)
	walletAddressService := ProvideWalletAddressService(walletAddressRepository, blockchainService, blockchainExplorerService)
	walletAddressController := ProvideWalletAddressController(walletAddressService)
	blockchainExplorerController := ProvideBlockchainExplorerController(blockchainExplorerService)
	container := &Container{
		BlockchainController:         blockchainController,
		WalletAddressController:      walletAddressController,
		BlockchainExplorerController: blockchainExplorerController,
	}
	return container
}

// wire.go:

type Container struct {
	BlockchainController         *controllers.BlockchainController
	WalletAddressController      *controllers.WalletAddressController
	BlockchainExplorerController *controllers.BlockchainExplorerController
}
