// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"athena/src/api/http/controllers"
	"athena/src/api/http/controllers/authentication"
	"athena/src/api/http/middlewares"
	"athena/src/database"
	"athena/src/services"
)

// Injectors from wire.go:

func GetContainer() *Container {
	databaseDatabase := database.GetInstance()
	blockchainRepository := ProvideBlockchainRepository(databaseDatabase)
	blockchainService := ProvideBlockchainService(blockchainRepository)
	blockchainController := ProvideBlockchainController(blockchainService)
	walletAddressRepository := ProvideWalletAddressRepository(databaseDatabase)
	blockchainExplorerRepository := ProvideBlockchainExplorerRepository(databaseDatabase)
	blockchainExplorerService := ProvideBlockchainExplorerService(blockchainExplorerRepository, blockchainService)
	walletAddressService := ProvideWalletAddressService(walletAddressRepository, blockchainService, blockchainExplorerService)
	walletAddressController := ProvideWalletAddressController(walletAddressService)
	blockchainExplorerController := ProvideBlockchainExplorerController(blockchainExplorerService)
	igpRepository := ProvideIGPRepository(databaseDatabase)
	igpService := ProvideIGPService(igpRepository)
	ipgService := ProvideIpgService(igpService)
	ipgController := ProvideIpgController(ipgService)
	depositRepository := ProvideDepositRepository(databaseDatabase)
	depositService := ProvideDepositService(depositRepository, walletAddressService)
	container := &Container{
		BlockchainController:         blockchainController,
		WalletAddressController:      walletAddressController,
		BlockchainExplorerController: blockchainExplorerController,
		IpgController:                ipgController,
		DepositService:               depositService,
		IgpService:                   igpService,
	}
	return container
}

func GetAuthenticationContainer() *AuthenticationContainer {
	databaseDatabase := database.GetInstance()
	userRepository := ProvideUserRepository(databaseDatabase)
	userService := ProvideUserService(userRepository)
	otpService := ProvideOTPService()
	registerService := ProvideRegisterService(userService, otpService)
	registerController := ProvideUserRegisterController(registerService)
	jwtService := ProvideJwtService()
	accessTokenRepository := ProvideAccessTokenRepository(databaseDatabase)
	accessTokenService := ProvideAccessTokenService(accessTokenRepository, jwtService, userRepository)
	twoFaService := ProvideTwoFaService()
	loginService := ProvideLoginService(userService, jwtService, accessTokenService, twoFaService, otpService)
	loginController := ProvideUserLoginController(loginService)
	accessTokenController := ProvideUserAccessTokenController(accessTokenService)
	recoveryPasswordService := ProvideRecoveryPasswordService(otpService, userService)
	recoverPasswordController := ProvideUserRecoverPasswordController(recoveryPasswordService)
	authenticationMiddleware := ProvideAuthenticationMiddleware(accessTokenService)
	authenticationContainer := &AuthenticationContainer{
		UserRegisterController:         registerController,
		UserLoginController:            loginController,
		UserAccessTokenController:      accessTokenController,
		UserRecoveryPasswordController: recoverPasswordController,
		AuthenticationMiddleware:       authenticationMiddleware,
	}
	return authenticationContainer
}

// wire.go:

type (
	Container struct {
		BlockchainController         *controllers.BlockchainController
		WalletAddressController      *controllers.WalletAddressController
		BlockchainExplorerController *controllers.BlockchainExplorerController
		IpgController                *controllers.IpgController
		DepositService               *services.DepositService
		IgpService                   *services.IGPService
	}

	AuthenticationContainer struct {
		UserRegisterController         *authentication.RegisterController
		UserLoginController            *authentication.LoginController
		UserAccessTokenController      *authentication.AccessTokenController
		UserRecoveryPasswordController *authentication.RecoverPasswordController
		AuthenticationMiddleware       *middlewares.AuthenticationMiddleware
	}
)
